export const ACTOR_FILTER = {
    reset_filter: "Сбросить Фильтр",
    view: "Вид",
    sort: "Сортировка",
    relevant: "Релевантно",
    alphabet: "А-Я",
    by_age: "По возрасту",
    main_info: "Основная Информация",
    gender: "Пол",
    male: "Муж.",
    quantityPhoto: "Кол-во Фото",
    quantityVideo: "Кол-во Видео",

    female: "Жен.",
    age: "Возраст",
    media: "Медиа",
    actors_compass: "Актёры Compass",
    advanced_search: "Расширенный Поиск",
    nationality: "Гражданство",
    specialization: "Специализация",
    cityOfResidence: "Город Проживания",
    legalStatus: "Правовой Статус",
    agency: "Агентство",
    externalData: "Внешние Данные",
    height: "Рост",
    weight: "Вес",
    clothingSize: "Размер Одежды",
    shoeSize: "Размер Обуви",
    hairLength: "Длина Волос",
    hairColor: "Цвет Волос",
    eyeColor: "Цвет Глаз",
    bodyPosition: "Телосложение",
    appearanceType: "Тип Внешности",
    features: "Особенности",
    skills: "Навыки",
    sport: "Спорт",
    dance: "Танцы",
    musicalInstruments: "Музыкальные Инструменты",
    singing: "Пение",
    foreignLanguages: "Иностранные Языки",
    drivingLicenses: "Права",
};
