import Navbar from "@/components/shared/navbar/Navbar";
import "@/styles/globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import StoreProvider from "./StoreProvider";

const montserrat = Montserrat({
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    subsets: ["latin"],
    variable: "--font-montserrat",
});
export const metadata: Metadata = {
    title: "Compass",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={montserrat.className}>
                <AntdRegistry>
                    <StoreProvider>
                        <div>
                            <Navbar />
                            {children}
                        </div>
                    </StoreProvider>
                </AntdRegistry>
            </body>
        </html>
    );
}
