export const FORM_TEXT = {
    create_profile: "Создать Профиль",
    edit_profile: "Редактировать Профиль",
    generalInfo: "Основная Информация",
    firstName: "Имя",
    lastName: "Фамилия",
    middleName: "Отчество",
    showAll: "Смотреть Все",
    gender: "Пол",
    male: "Муж.",
    female: "Жен.",
    logout: "Выйти",
    birthDate: "Дата Рождения",
    nationality: "Гражданство",
    specialization: "Специализация",
    cityOfResidence: "Город Проживания",
    legalStatus: "Правовой Статус",
    agency: "Агентство",
    externalData: "Внешние Данные",
    height: "Рост",
    weight: "Вес",
    clothingSize: "Размер Одежды",
    shoeSize: "Размер Обуви",
    hairLength: "Длина Волос",
    hairColor: "Цвет Волос",
    eyeColor: "Цвет Глаз",
    bodyPosition: "Телосложение",
    appearanceType: "Тип Внешности",
    features: "Особенности",
    skills: "Навыки",
    sport: "Спорт",
    dance: "Танцы",
    musicalInstruments: "Музыкальные Инструменты",
    singing: "Пение",
    foreignLanguages: "Иностранные Языки",
    drivingLicenses: "Права",
    education: "Образование",
    university: "Университет",
    faculty: "Факультет",
    yearsOfStudy: "Годы Обучения",
    theaterWork: "Работа в Театре",
    theater: "Театр",
    performances: "Спектакли",
    yearsOfPerformance: "Годы Обучения",
    addMore: "Добавить ещё", // This seems to be a button or link text
    movies: "Фильмы",
    movieTitle: "Название",
    role: "Роль",
    releaseYear: "Год Выпуска",
    awards: "Награды",
    awardName: "Название",
    position: "Позиция",
    year: "Год",
    additionalInfo: "Дополнительная Информация",
    comments: "Комментарий",
    remove: "Удалить",
    uploadButton: "Выбрать",
    media: "Медиа",
    photos: "Фото",
    videos: "Видео",
    add: "Добавить",
    socialNetworks: "Социальные Сети",
    socialNetworkName: "Название",
    socialNetworkLink: "Ссылка",
    contactInfo: "Контактная Информация",
    contacts: "Контакты",
    contactName: "Имя",
    contactNumber: "Номер",
    addMoreContact: "Добавить ещё",
    confirm_title: "Подтвердите Действие",
    data_correct: "Вы Уверены, что все данные верны?",
    accept: "Подтвердить",
    cancel: "Отмена",
    success: "Успешно",
    failure: "Повторите ещё раз",
    ok: "Ок",
    submitted: "Ваша заявка отправлена.",
};
